module.exports = [
  'Total Nonfarm',
  'Total Private',
  'Goods Producing',
  'Service-Providing',
  'Private Service Providing',
  'Mining and Logging',
  'Logging',
  'Mining, Quarrying, and Oil and Gas Extraction',
  'Oil and Gas Extraction',
  'Mining (except Oil and Gas)',
  'Coal Mining',
  'Metal Ore Mining',
  'Support Activities for Mining',
  'Drilling Oil and Gas Wells',
  'Support Activities for Oil and Gas Operations',
  'Mining, Logging and Construction',
  'Construction',
  'Construction of Buildings',
  'Residential Building Construction',
  'Nonresidential Building Construction',
  'Heavy and Civil Engineering Construction',
  'Utility System Construction',
  'Land Subdivision',
  'Highway, Street, and Bridge Construction',
  'Other Heavy and Civil Engineering Construction',
  'Specialty Trade Contractors',
  'Foundation, Structure, and Building Exterior Contractors',
  'Building Equipment Contractors',
  'Building Finishing Contractors',
  'Other Specialty Trade Contractors',
  'Manufacturing',
  'Durable Goods',
  'Wood Product Manufacturing',
  'Sawmills and Wood Preservation',
  'Veneer, Plywood, and Engineered Wood Product Manufacturing',
  'Other Wood Product Manufacturing',
  'Nonmetallic Mineral Product Manufacturing',
  'Cement and Concrete Product Manufacturing',
  'Primary Metal Manufacturing',
  'Iron and Steel Mills and Ferroalloy Manufacturing',
  'Foundries',
  'Fabricated Metal Product Manufacturing',
  'Architectural and Structural Metals Manufacturing',
  'Machine Shops; Turned Product; and Screw, Nut, and Bolt Manufacturing',
  'Other Fabricated Metal Product Manufacturing',
  'Machinery Manufacturing',
  'Agriculture, Construction, and Mining Machinery Manufacturing',
  'Industrial Machinery Manufacturing',
  'Commercial and Service Industry Machinery Manufacturing',
  'Metalworking Machinery Manufacturing',
  'Engine, Turbine, and Power Transmission Equipment Manufacturing',
  'Other General Purpose Machinery Manufacturing',
  'Computer and Electronic Product Manufacturing',
  'Computer and Peripheral Equipment Manufacturing',
  'Electronic Computer Manufacturing',
  'Communications Equipment Manufacturing',
  'Semiconductor and Other Electronic Component Manufacturing',
  'Bare Printed Circuit Board Manufacturing',
  'Semiconductor and Related Device Manufacturing',
  'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing',
  'Electrical Equipment, Appliance, and Component Manufacturing',
  'Household Appliance Manufacturing',
  'Electrical Equipment Manufacturing',
  'Transportation Equipment Manufacturing',
  'Motor Vehicle Manufacturing',
  'Motor Vehicle Body and Trailer Manufacturing',
  'Motor Vehicle Parts Manufacturing',
  'Aerospace Product and Parts Manufacturing',
  'Ship and Boat Building',
  'Furniture and Related Product Manufacturing',
  'Household and Institutional Furniture and Kitchen Cabinet Manufacturing',
  'Miscellaneous durable goods manufacturing',
  'Medical Equipment and Supplies Manufacturing',
  'Other Miscellaneous Manufacturing',
  'Jewelry and Silverware Manufacturing',
  'Non-Durable Goods',
  'Food Manufacturing',
  'Grain and Oilseed Milling',
  'Fruit and Vegetable Preserving and Specialty Food Manufacturing',
  'Dairy Product Manufacturing',
  'Animal Slaughtering and Processing',
  'Seafood Product Preparation and Packaging',
  'Bakeries and Tortilla Manufacturing',
  'Other Food Manufacturing',
  'Beverage and Tobacco Product Manufacturing',
  'Beverage Manufacturing',
  'Tobacco Manufacturing',
  'Textile Mills',
  'Fiber, Yarn, and Thread Mills',
  'Fabric Mills',
  'Textile and Fabric Finishing and Fabric Coating Mills',
  'Textile Product Mills',
  'Textile Furnishings Mills',
  'Apparel Manufacturing',
  'Apparel Knitting Mills',
  'Cut and Sew Apparel Manufacturing',
  'Paper Manufacturing',
  'Pulp, Paper, and Paperboard Mills',
  'Converted Paper Product Manufacturing',
  'Printing and Related Support Activities',
  'Petroleum and Coal Products Manufacturing',
  'Chemical Manufacturing',
  'Basic Chemical Manufacturing',
  'Pharmaceutical and Medicine Manufacturing',
  'Soap, Cleaning Compound, and Toilet Preparation Manufacturing',
  'Plastics and Rubber Products Manufacturing',
  'Plastics Product Manufacturing',
  'Rubber Product Manufacturing',
  'Trade, Transportation, and Utilities',
  'Wholesale Trade',
  'Merchant Wholesalers, Durable Goods',
  'Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers',
  'Furniture and Home Furnishing Merchant Wholesalers',
  'Lumber and Other Construction Materials Merchant Wholesalers',
  'Professional and Commercial Equipment and Supplies Merchant Wholesalers',
  'Household Appliances and Electrical and Electronic Goods Merchant Wholesalers',
  'Hardware, and Plumbing and Heating Equipment and Supplies Merchant Whole',
  'Machinery, Equipment, and Supplies Merchant Wholesalers',
  'Miscellaneous Durable Goods Merchant Wholesalers',
  'Merchant Wholesalers, Nondurable Goods',
  'Paper and Paper Product Merchant Wholesalers',
  'Apparel, Piece Goods, and Notions Merchant Wholesalers',
  'Grocery and Related Product Merchant Wholesalers',
  'Chemical and Allied Products Merchant Wholesalers',
  'Miscellaneous Nondurable Goods Merchant Wholesalers',
  'Wholesale Electronic Markets and Agents and Brokers',
  'Retail Trade',
  'Motor Vehicle and Parts Dealers',
  'Automobile Dealers',
  'Other Motor Vehicle Dealers',
  'Automotive Parts, Accessories, and Tire Stores',
  'Furniture and Home Furnishings Stores',
  'Furniture Stores',
  'Home Furnishings Stores',
  'Electronics and Appliance Stores',
  'Building Material and Garden Equipment and Supplies Dealers',
  'Building Material and Supplies Dealers',
  'Food and Beverage Stores',
  'Grocery Stores',
  'Specialty Food Stores',
  'Beer, Wine, and Liquor Stores',
  'Health and Personal Care Stores',
  'Gasoline Stations',
  'Clothing and Clothing Accessories Stores',
  'Clothing Stores',
  'Jewelry, Luggage, and Leather Goods Stores',
  'Sporting Goods, Hobby, Musical Instrument, and Book Stores',
  'Sporting Goods, Hobby, and Musical Instrument Stores',
  'Book Stores and News Dealers',
  'General Merchandise Stores',
  'Department Stores',
  'General Merchandise Stores, including Warehouse Clubs and Supercenters',
  'Miscellaneous Store Retailers',
  'Office Supplies, Stationery, and Gift Stores',
  'Used Merchandise Stores',
  'Other Miscellaneous Store Retailers',
  'Nonstore Retailers',
  'Electronic Shopping and Mail-Order Houses',
  'Transportation, Warehousing, and Utilities',
  'Utilities',
  'Electric Power Generation, Transmission and Distribution',
  'Natural Gas Distribution',
  'Transportation and Warehousing',
  'Air Transportation',
  'Scheduled Air Transportation',
  'Rail Transportation',
  'Water Transportation',
  'Truck Transportation',
  'General Freight Trucking',
  'Specialized Freight Trucking',
  'Transit and Ground Passenger Transportation',
  'Taxi and Limousine Service',
  'School and Employee Bus Transportation',
  'Pipeline Transportation',
  'Support Activities for Transportation',
  'Support Activities for Air Transportation',
  'Support Activities for Water Transportation',
  'Support Activities for Road Transportation',
  'Freight Transportation Arrangement',
  'Couriers and Messengers',
  'Warehousing and Storage',
  'Information',
  'Publishing Industries (except Internet)',
  'Newspaper, Periodical, Book, and Directory Publishers',
  'Software Publishers',
  'Motion Picture and Sound Recording Industries',
  'Motion Picture and Video Industries',
  'Motion Picture and Video Production',
  'Broadcasting (except Internet)',
  'Radio and Television Broadcasting',
  'Cable and Other Subscription Programming',
  'Telecommunications',
  'Wired and Wireless Telecommunications Carriers',
  'Wired Telecommunications Carriers',
  'Wireless Telecommunications Carriers (except Satellite)',
  'Data Processing, Hosting, and Related Services',
  'Other Information Services',
  'Financial Activities',
  'Finance and Insurance',
  'Credit Intermediation and Related Activities including Monetary Authorities - Central Bank',
  'Depository Credit Intermediation including Monetary Authorities - Central Bank',
  'Commercial Banking',
  'Nondepository Credit Intermediation',
  'Activities Related to Credit Intermediation',
  'Financial Investments and Related Activities including Financial Vehicles',
  'Securities and Commodity Contracts Intermediation and Brokerage',
  'Investment Banking and Securities Dealing',
  'Securities Brokerage',
  'Other Financial Investment Activities including Financial Vehicles',
  'Insurance Carriers and Related Activities',
  'Insurance Carriers',
  'Direct Life Insurance Carriers',
  'Direct Health and Medical Insurance Carriers',
  'Direct Property and Casualty Insurance Carriers',
  'Agencies, Brokerages, and Other Insurance Related Activities',
  'Real Estate and Rental and Leasing',
  'Real Estate',
  'Lessors of Real Estate',
  'Offices of Real Estate Agents and Brokers',
  'Activities Related to Real Estate',
  'Rental and Leasing Services',
  'Automotive Equipment Rental and Leasing',
  'Consumer Goods Rental',
  'General Rental Centers',
  'Commercial and Industrial Machinery and Equipment Rental and Leasing',
  'Professional and Business Services',
  'Professional, Scientific, and Technical Services',
  'Legal Services',
  'Accounting, Tax Preparation, Bookkeeping, and Payroll Services',
  'Architectural, Engineering, and Related Services',
  'Specialized Design Services',
  'Computer Systems Design and Related Services',
  'Management, Scientific, and Technical Consulting Services',
  'Scientific Research and Development Services',
  'Advertising, Public Relations, and Related Services',
  'Other Professional, Scientific, and Technical Services',
  'Management of Companies and Enterprises',
  'Administrative and Support and Waste Management and Remediation Services',
  'Administrative and Support Services',
  'Office Administrative Services',
  'Facilities Support Services',
  'Employment Services',
  'Temporary Help Services',
  'Business Support Services',
  'Telephone Call Centers',
  'Travel Arrangement and Reservation Services',
  'Investigation and Security Services',
  'Investigation, Guard, and Armored Car Services',
  'Services to Buildings and Dwellings',
  'Other Support Services',
  'Waste Management and Remediation Services',
  'Education and Health Services',
  'Educational Services',
  'Elementary and Secondary Schools',
  'Junior Colleges',
  'Colleges, Universities, and Professional Schools',
  'Other Schools and Instruction',
  'Health Care and Social Assistance',
  'Ambulatory Health Care Services',
  'Offices of Physicians',
  'Offices of Dentists',
  'Offices of Other Health Practitioners',
  'Outpatient Care Centers',
  'Medical and Diagnostic Laboratories',
  'Home Health Care Services',
  'Other Ambulatory Health Care Services',
  'Hospitals',
  'General Medical and Surgical Hospitals',
  'Psychiatric and Substance Abuse Hospitals',
  'Specialty (except Psychiatric and Substance Abuse) Hospitals',
  'Nursing and Residential Care Facilities',
  'Nursing Care Facilities (Skilled Nursing Facilities)',
  'Residential Intellectual and Developmental Disability, Mental Health and Substance Abuse Facilities',
  'Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly',
  'Other Residential Care Facilities',
  'Social Assistance',
  'Individual and Family Services',
  'Services for the Elderly and Persons with Disabilities',
  'Community Food and Housing, and Emergency and Other Relief Services',
  'Vocational Rehabilitation Services',
  'Child Day Care Services',
  'Leisure and Hospitality',
  'Arts, Entertainment, and Recreation',
  'Performing Arts, Spectator Sports, and Related Industries',
  'Performing Arts Companies',
  'Spectator Sports',
  'Promoters of Performing Arts, Sports, and Similar Events',
  'Independent Artists, Writers, and Performers',
  'Museums, Historical Sites, and Similar Institutions',
  'Amusement, Gambling, and Recreation Industries',
  'Amusement Parks and Arcades',
  'Gambling Industries',
  'Other Amusement and Recreation Industries',
  'Fitness and Recreational Sports Centers',
  'Accommodation and Food Services',
  'Accommodation',
  'Traveler Accommodation',
  'Hotels (except Casino Hotels) and Motels',
  'Casino Hotels',
  'Food Services and Drinking Places',
  'Special Food Services',
  'Drinking Places (Alcoholic Beverages)',
  'Restaurants and Other Eating Places',
  'Full-Service Restaurants',
  'Limited-Service Restaurants and Other Eating Places',
  'Other Services',
  'Repair and Maintenance',
  'Automotive Repair and Maintenance',
  'Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance',
  'Personal and Household Goods Repair and Maintenance',
  'Personal and Laundry Services',
  'Personal Care Services',
  'Drycleaning and Laundry Services',
  'Other Personal Services',
  'Religious, Grantmaking, Civic, Professional, and Similar Organizations',
  'Religious Organizations',
  'Grantmaking and Giving Services',
  'Social Advocacy Organizations',
  'Civic and Social Organizations',
  'Business, Professional, Labor, Political, and Similar Organizations',
  'Government',
  'Federal Government',
  'National Security',
  'Federal Government excluding Department of Defense',
  'Federal Government excluding Postal Service',
  'Federal Government excluding Postal Service, Department of Defense, Ship Building, and Hospitals',
  'Federal Government Hospitals',
  'Department of Defense',
  'Department of Defense, including Ship Building',
  'Department of Defense, including Ship Building and Hospitals',
  'U.S. Postal Service',
  'State Government',
  'State Government Educational Services',
  'State Government Excluding Education',
  'State Government Hospitals',
  'State Government excluding Educational Services and Hospitals',
  'Local Government',
  'Indian Tribes',
  'Local Government Educational Services',
  'Local Government excluding Educational Services',
  'Transportation',
  'Local Government Hospitals',
  'Local Government Elementary and Secondary Education',
  'Total State and Local Government',
  'District of Columbia Government'
];
